"""
Django settings for Db_exemple project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR,'templates')
TEMPLATES_DIR_exemple = os.path.join(BASE_DIR,'exemple_app/templates')
TEMPLATES_DIR_forms = os.path.join(BASE_DIR,'forms_app/templates')
TEMPLATES_DIR_user = os.path.join(BASE_DIR,'user_app/templates')
TEMPLATES_DIR_cbv = os.path.join(BASE_DIR,'CBV_app/templates')
STATIC_DIR = os.path.join(BASE_DIR,'static')
MEDIA_DIR = os.path.join(BASE_DIR,'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yo7g6#&o&l!ah8iyu^1-ooa)2dm-z6%bfesybs$!s*n828q6!%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exemple_app',
    'forms_app',
    #'auth_app',    #app pentru user customizat. Doar una trebuie activata la inceput de proiect!
    'user_app',     #app pentru user predefinit. Doar una trebuie activata la inceput de proiect!
    'CBV_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Db_exemple.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                TEMPLATES_DIR,
                TEMPLATES_DIR_forms,
                TEMPLATES_DIR_exemple,
                TEMPLATES_DIR_user,
                TEMPLATES_DIR_cbv,
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Db_exemple.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_exemple_user',
        'USER': 'postgres',
        'PASSWORD': 'PostGres?',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

INTERNAL_IPS = ['127.0.0.1']    #configuratie de la PostgreSQL

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
# pip install bcrypt
# pip install django[argon2]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]
#aici adaugi criteriile de validare pe diferite campuri din procesul de autentificare
AUTH_PASSWORD_VALIDATORS = [
    {   #user!=parola
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {   
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        #'OPTIONS':{'min_lenght':8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR,
]

MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'

#aceast atribut s-a adaugat pentru aplicatia user_app
LOGIN_URL = '/user_app/user_auth'